### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by pataquets**
Adds Dockerfile to build Docker image, using community maintained official [Ruby](https://hub.docker.com/r/_/ruby/) 2.x latest on Alpine Linux (a minimal, tiny distro) as a base image. You can find an automated build here: https://hub.docker.com/r/pataquets/htty/

How to test:

```
$ docker run --rm -it pataquets/htty
```

It would be desirable to create an _official_ image at Docker Hub. You can even set up an automated build to trigger on each commit.
The steps would be:
- The project owner signs up.
- (If multiple persons in project/packging team) Create an organization 'htty'.
- Set up an 'automated build', linked to the Github repository.
- Profit!
  Thus the Docker image name will be `htty/htty`.

### CODE REVIEW

**Comment by deiga** [comment]
Why do you that this should be a part of the repo?

**Comment by pataquets** [comment]
- Helps document install reqs
- Eases new devel onboarding by providing quick local environment
- Enables Docker image [automated builds](https://docs.docker.com/v1.7/docker/docker-hub/builds/), if desired
- Helps others test the app quickly
- Install reqs can be maintained as the app evolves
- Adds another distribution format
- Adds more awesomeness and it's cool :smile:

**Comment by njonsson** [comment]
Merged in f5fbedfff743c03e838320e53ea5ade9b808106e. Thanks, @pataquets!

**Comment by pataquets** [comment]
You're welcome. Thanks for making htty available.
If you want to create an [automated build](https://docs.docker.com/v1.7/docker/docker-hub/builds/) to publish htty Docker images on Docker Hub, please check the OP.
Let me know if I can be of any help.

**Comment by pataquets** [comment]
Bump. Any plan to create an 'official' image (automated build) on Docker Hub?

**Comment by njonsson** [comment]
@pataquets, thanks for the nudge. I’ve created an [official image](https://hub.docker.com/r/gethtty/htty/) and [automated build](https://cloud.docker.com/gethtty/repository/docker/gethtty/htty/builds). Let me know if you have any suggestions.

**Comment by pataquets** [comment]
You're welcome, @njonsson . Also, thanks for adding me to gethtty organization on Docker Hub.
However, I've checked the gethty/htty image (first link) and it is not an Automated Build (ie, based on source repo), but I imagine it is built and later pushed to DH. Didn't logged to Docker Cloud second link, since it is Docker's commercial service an not public. AB's should live in public DH org account.
```
$ docker search gethtty
NAME           DESCRIPTION   STARS     OFFICIAL   AUTOMATED
gethtty/htty                                     0                    
```
Creating an AB provides way much more trust, since the source git repo is connected to the DH build and uploaded image always comes from the source code build and it can be viewed publicly on Github.
With my curent gethtty org membership on DH, I can't create an AB, since it requires Github-repo owner access in order to DH to add the webhooks and deploy keys.

AB docs: https://docs.docker.com/v1.7/docker/docker-hub/builds/
Ping me if you need help.

**Comment by njonsson** [comment]
@pataquets, thanks for the helpful explanation. I’ve created [a public Docker Hub Automated Build](https://hub.docker.com/r/gethtty/htty/), I believe according to your instructions.

**Comment by pataquets** [comment]
Checked, now it is an AB. Thank you.

**Comment by pataquets** [comment]
BTW, when you add new version tags from now on, they can be mapped to Docker image tags, also. Previous versions won't work b/c they don't have Dockerfile previously.

**Pull request merged**
